### ISSUE TITLE
Issue: dictionary.subscript.getter 문제 

### ISSUE THREAD

**Issue by eeeesong** [codesquad-members-2021/swift-photos-06#13]
<img width="486" alt="스크린샷 2021-03-26 오후 9 56 22" src="https://user-images.githubusercontent.com/72188416/112642768-fad5a780-8e86-11eb-8303-bfb53788fdb5.png">

DoodleViewController에서 이미지 다운로드 진행 시, 
(체감) 10번 중에 1번 꼴로 `dictionary.subscript.getter` 문제가 발생한다.

**Comment by eeeesong** [comment]
### 발생 배경
- doodle image 다운로드 최적화를 위하여 2가지 경로로 다운로드 진행
   1. **background (@backgroundDownloadQueue)**
      DoodleViewController가 init하는 ImageManager의 메소드인 `startDownloadingAtBackground()`를 통해 객체 초기화와 동시에 일괄 다운로드 
   2. **cell init time (@cellInitTimeDownloadQueue)**
      CollectionView의 메소드 `collectionView(cellForItemAt indexPath: )` 호출 시, background에서 생성된 이미지가 없을 경우 ([URL: UIImage] 에서 URL 키 통해 생성 확인) 전용 queue에 작업 목록 더함
- 두 queue의 작업 결과물을 저장하는 dictionary는 공동 사용
- 그렇다 보니 dictionary 업데이트 과정에서 동시에 write이 일어나는 등의 교차 작업 발생 시 오류가 발생하는 것으로 추정

**Comment by eeeesong** [comment]
### 해결 방안
- dictionary는 thread-free하지 않다는 것을 알게 되어 다음과 같은 조치를 취함 ([참고 링크](https://www.reddit.com/r/swift/comments/f1qevc/is_reading_from_dictionaries_threadsafe/))
- dictionary write 시 async, barrier 추가 (`(flags: .barrier)`)
   - barrier를 통해 하나의 value를 업데이트하는 동안 다른 곳에서 업데이트가 일어나지 못하도록 막는다.
- dictionary read 시 sync로 작동하도록 설정
   - async로 작성 시 이미지가 원활하게 업데이트되지 않음. 명확한 이유는 아직 잘 모르겠음... (이 부분은 더 공부가 필요)
- ImageDownloder class에 dictionary 업데이트만을 위한 queue 생성
  - barrier가 있더라도 background/cellInitTime queue 각각에서 다른 key의 dictionary value에 접근하려 하면 오류가 발생할 수 있기 때문에 개별 queue를 생성.

> dictionary Queue
```swift
///ImageDownloader 이니셜라이저 내부
dictionaryUpdateQueue = DispatchQueue(label: "dictionary",
                                      qos: .userInitiated,
                                      attributes: .concurrent,
                                      autoreleaseFrequency: .workItem,
                                      target: nil)
```

> read 방식 처리
```swift
func getCachedImageFrom(url: URL) -> UIImage? {
    var image: UIImage?
    dictionaryUpdateQueue.sync {
        image = self.cachedImages[url]
    }
    return image
}

func getDataTaskFrom(url: URL) -> URLSessionTask? {
    var task: URLSessionTask?
    dictionaryUpdateQueue.sync {
        task = self.imagesDownloadTasks[url]
    }
    return task
}
```

> write 방식 처리
```swift
func downloadImage(inQueue queue: DispatchQueue,
                   imageURL: URL,
                   completionHandler: @escaping (UIImage) -> Void,
                   placeholderImage: UIImage) {
    
    guard getDataTaskFrom(url: imageURL) == nil else { return }
    
    let task = URLSession.shared.dataTask(with: imageURL) { (data, response, error) in
        
        guard error == nil else {
            completionHandler(placeholderImage)
            return
        }
        
        if let data = data, let image = UIImage(data: data) {
            self.dictionaryUpdateQueue.async(flags: .barrier) {
                self.cachedImages[imageURL] = image
            }
            completionHandler(image)
        } else {
            self.dictionaryUpdateQueue.async(flags: .barrier) {
                self.cachedImages[imageURL] = placeholderImage
            }
            completionHandler(placeholderImage)
        }
    }
    
    dictionaryUpdateQueue.async(flags: .barrier) {
        self.imagesDownloadTasks[imageURL] = task
    }
    
    queue.async { ///작업 배당 queue는 background or cellInitTime
        task.resume()
    }
}
```

**Comment by JacksonPk** [comment]
확인하였습니다,롤로. 자주 애러가 나는 곳인 getChahed쪽을 해결해 주셨네요. 읽어보니 원인이 정확하진 않지만 말씀하신대로 데이터 무결성 문제인거 같아요. 일단 테스트 결과가 더 향상돼서 main으로 올려도 될 것 같아요.

**Comment by eeeesong** [comment]
> 확인하였습니다,롤로. 자주 애러가 나는 곳인 getChahed쪽을 해결해 주셨네요. 읽어보니 원인이 정확하진 않지만 말씀하신대로 데이터 무결성 문제인거 같아요. 일단 테스트 결과가 더 향상돼서 main으로 올려도 될 것 같아요.

우선 feature-makeView 쪽에 push를 해뒀습니다.
테스트 결과가 좋으면 main에 올려주세요! 감사합니다

**Comment by JacksonPk** [comment]
> > 확인하였습니다,롤로. 자주 애러가 나는 곳인 getChahed쪽을 해결해 주셨네요. 읽어보니 원인이 정확하진 않지만 말씀하신대로 데이터 무결성 문제인거 같아요. 일단 테스트 결과가 더 향상돼서 main으로 올려도 될 것 같아요.
> 
> 우선 feature-makeView 쪽에 push를 해뒀습니다.
> 테스트 결과가 좋으면 main에 올려주세요! 감사합니다

롤로 오늘 하루동안 중간중간 해봤는데 끊긴적이 없네요. 
이 브랜치를 main으로 merge하도록 할게요.

**Comment by eeeesong** [comment]
> > > 확인하였습니다,롤로. 자주 애러가 나는 곳인 getChahed쪽을 해결해 주셨네요. 읽어보니 원인이 정확하진 않지만 말씀하신대로 데이터 무결성 문제인거 같아요. 일단 테스트 결과가 더 향상돼서 main으로 올려도 될 것 같아요.
> 
> > 
> 
> > 우선 feature-makeView 쪽에 push를 해뒀습니다.
> 
> > 테스트 결과가 좋으면 main에 올려주세요! 감사합니다
> 
> 
> 
> 롤로 오늘 하루동안 중간중간 해봤는데 끊긴적이 없네요. 
> 
> 이 브랜치를 main으로 merge하도록 할게요.
> 
>  

오 넵! 저도 중간중간 봤는데 괜찮았습니다 :)
그럼 이 내용으로 리드미 정리해볼게요~!
낼 오전에 하고 오후쯤에 슬랙에 공유드리겠습니다
